apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-kafka-demo
  labels:
    app: temporal-kafka-demo
spec:
  replicas: {{ .Values.workerWithoutStarterCount }}
  selector:
    matchLabels:
      app: temporal-kafka-demo
  template:
    metadata:
      labels:
        app: temporal-kafka-demo
    spec:
      containers:
        - name: temporal-kafka-demo
          image: "thycoder/temporal-kafka-demo:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /opt
            - name: env
              mountPath: /app/.env
              subPath: .env
          env:
            # Define the environment variable
            - name: SHOULD_START_WORKFLOWS
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SHOULD_START_WORKFLOWS
                  name: special-config
                  # Specify the key associated with the value
                  key: special.slave
      volumes:
        - name: data
          emptyDir: {}
        - name: env
          configMap:
            name: temporal-kafka-demo-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-kafka-demo-with-starter
  labels:
    app: temporal-kafka-demo-with-starter
spec:
  replicas: {{ .Values.workerWithStarterCount }}
  selector:
    matchLabels:
      app: temporal-kafka-demo-with-starter
  template:
    metadata:
      labels:
        app: temporal-kafka-demo-with-starter
    spec:
      containers:
        - name: temporal-kafka-demo-with-starter
          image: "thycoder/temporal-kafka-demo:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /opt
          env:
            # Define the environment variable
            - name: SHOULD_START_WORKFLOWS
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SHOULD_START_WORKFLOWS
                  name: special-config
                  # Specify the key associated with the value
                  key: special.master
      volumes:
        - name: data
          emptyDir: {}

