# Default values for temporal-kafka-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
producerCount: 200
consumerCount: 2
kafkaTopic: preonline
kafkaProducers: kafka.default.svc.cluster.local:9092
kafkaConsumers: kafka.default.svc.cluster.local:9092
kafkaConsumerGroup: consumer-group-id
temporalFrontend: temporaltest-frontend.default.svc.cluster.local:7233

workerWithoutStarterCount: 4

workerWithStarterCount: 1

image:
  pullPolicy: Always
  tag: "latest"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
